const sidebars = {
  marketplaceSidebar: [
    {
      type: 'html',
      value: `
        <div style="display: flex; align-items: center;">
          <img src="/img/markett.svg" alt="Logo" style="width: 24px; height: 24px; margin-right: 8px;" />
          <span>Marketplace</span>
        </div>
      `,
    },
    {
      type: 'autogenerated',
      dirName: 'marketplace', // Folder name inside 'docs' folder
    },
  ],
  supplySidebar: [
    {
      type: 'html',
      value: `
        <div style="display: flex; align-items: center;">
          <img src="/img/supply.svg" alt="Logo" style="width: 24px; height: 24px; margin-right: 8px;" />
          <span>ERP/POS</span>
        </div>
      `,
    },
    {
      type: 'autogenerated',
      dirName: 'supply', // Folder name inside 'docs' folder
    },
  ],
};

export default sidebars;
