const sidebars = {
  marketplaceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'marketplace', // Folder name inside 'docs' folder
    },
  ],
  supplySidebar: [
    {
      type: 'autogenerated',
      dirName: 'supply', // Folder name inside 'docs' folder
    },
  ],
};

export default sidebars;
